package org.romaframework.scaffolding.factory;


import org.romaframework.core.entity.EntityHelper;
import org.romaframework.core.factory.AbstractFactory;
import org.romaframework.scaffolding.domain.entity.Customer;
import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Component;

/**
 * Factory class for Customer entity. It's registered in the IoC configuration files and is used by Roma components to create objects of kind Sede. 
 * <br/>Use EntityHelper.createObject() to create objects using the its factory.
 * <br/>This class was generated by Roma Meta Framework CRUD wizard.
 * @see EntityHelper  
 */ 
@Component("CustomerFactory")
@Lazy
public class CustomerFactory extends AbstractFactory<Customer> {
  @Override
  public Customer create() {
    return new Customer();
  }
}
